### ISSUE TITLE
Querying All Swaps within a timestamp interval (first: 1000>)

### ISSUE THREAD

**Issue by 10dimensions** [Uniswap/uniswap-v3-subgraph#40]
`message: 'The `first` argument must be between 0 and 1000, but is 10000'`

It seems the Graph is limiting the number of all swaps to a cap of 1000. 
Can this be overridden ? Or is there any alternate solution ?

**Comment by benesjan** [comment]
Hello,
you can fetch the next 1000 by using the skip: 1000 parameter and continue like that until you have everything.

**Comment by 10dimensions** [comment]
Thanks @benesjan . This did help out.
But in addition I found that even skip has a maximum permitted value of up to 5000.

Unfortunately, my use case involves a monthly-data analysis, which might involve up to 100,000 items as well.
If TheGraph is not possible to achieve it, can you point at other resources?

**Comment by benesjan** [comment]
Hello, you could sort the data by timestamp and then instead of skip use the last timestamp as the min timestamp.

**Comment by 10dimensions** [comment]
Thanks @benesjan . Working with the proposed technique.

**Comment by drewgillen** [comment]
@benesjan How would you recommend loading a lot of pool hour data? Filtering by a Unix Time stamp or using the skip function?
